### ISSUE TITLE
cpanm

### ISSUE THREAD

**Issue by ghost** [PDLPorters/extutils-f77#6]
regarding https://github.com/PDLPorters/extutils-f77/pull/5/commits/4e464b574105da1d438ac1ce7fe8137e19b51d40

while cleaning up the documentation

I had the idea to use Nokubi Takatsugu's README.en (from File::MMagic)

as some sort of README template

so, I would rather see the following

which reverts to (a typographical error corrected) v.1.21 README

and would add the recommendation for cpanm 

```
2. Install

Extract archive file.
Change current directory to ExtUtils-F77-x.xx ("x.xx" is version
number).
Type "perl Makefile.PL" to create Makefile.
Type "make" to build module.
Type "make test" to test build.
Type "make install" to install.

Or run "cpanm ExtUtils::F77". To install cpanm, see
https://metacpan.org/pod/App::cpanminus#INSTALLATION
```

**Comment by mohawk2** [comment]
I would rather not see such a reversion from best practice. What possible benefit is there to introducing potential errors, while taking longer and being more fiddly?

**Comment by ghost** [comment]
> possible benefit

the query is made in singular, not plural, form

the App::cpanminus module's documentation lists .deb, .rpm, and FreeBSD ports

at least one Linux distribution doesn't maintain an online package repository

I don't want to burden the reader to install more modules

to read more modules' documentation

to expain how to edit an /etc/sudoers file

**Comment by mohawk2** [comment]
They'd still need to use `sudo`, but that's not explained. And your solution to having to install a module (really an application) is to instead have people do all the things manually, including downloading the CPAN distro file? That's your idea of the *easy* option?

**Comment by ghost** [comment]
I'm not going to be convinced about App::cpanminus.

The pod section itself in the hyperlink in https://github.com/PDLPorters/extutils-f77/commit/4e464b574105da1d438ac1ce7fe8137e19b51d40 provides several ways to install.

**Comment by karlglazebrook** [comment]
I think it's fine for the README to give instructions for manual installation. I do that a lot, esp. with a module as finicky as this one.

**Comment by ghost** [comment]
I would ask the developers to make a README file decision on the 2. Install section.

That this either be implemented as in https://github.com/PDLPorters/extutils-f77/commit/4e464b574105da1d438ac1ce7fe8137e19b51d40, or as I suggested in https://github.com/PDLPorters/extutils-f77/issues/6#issue-391678853.

It is distracting to have 2 separate links as the (older) https://github.com/PDLPorters/extutils-f77/commit/4e464b574105da1d438ac1ce7fe8137e19b51d40, and the (newer) https://github.com/PDLPorters/extutils-f77/commit/2b1a8e7a893b6ecfa37704526a295da4551d4d71.

Obviously the above has nothing to do with https://github.com/PDLPorters/extutils-f77/commit/68bae4d3abfcb816e853a45573d3fa534d2ebdf6, where README file 6. See also section had been overwritten - I believe that the pod format markup surrounding the two MetaCPAN modules is not for README files - and the tests-improve branch README file 6. See also section should be reverted to its content prior to that commit.

**Comment by ghost** [comment]
implemented verbatim as in https://github.com/PDLPorters/extutils-f77/commit/4e464b574105da1d438ac1ce7fe8137e19b51d40, or verbatim as I suggested in https://github.com/PDLPorters/extutils-f77/issues/6#issue-391678853
