### ISSUE TITLE
SEE ALSO

### ISSUE THREAD

**Issue by ghost** [PDLPorters/extutils-f77#7]
regarding the F77.pm SEE ALSO section, I would prefer simply the following.

`L<PDL> (PDL::Minuit and PDL::Slatec), L<PGPLOT>`

**Comment by karlglazebrook** [comment]
I'd suggest more explanatory text like 'This module is used by ...'

**Comment by ghost** [comment]
A brief and random review of some MetaCPAN modules, including some PDL dependency modules, where a SEE ALSO section is present in a .pm file, indicates that such sections often solely list other MetaCPAN modules (which are factually hyperlinked).

If the developers are more inclined towards explanatory text than towards a limited list of hyperlinked modules, perhaps something along the lines of the below might be considered to simply add after the current content, where if such change were made the SEE ALSO section would constitute a single paragraph.

`It is also used by L<PDL> (PDL::Minuit and PDL::Slatec), the interfaces implemented, respectively, to the Minuit minimization library from CERN, and to parts of the slatec library, the latter also serving the purpose of showing how to interface PDL to an external library.`

**Comment by karlglazebrook** [comment]
Seems reasonable to me. I've made an edit on the tests-improve branch

**Comment by ghost** [comment]
This issue refers to the F77.pm SEE ALSO section, not the README file.

**Comment by ghost** [comment]
I would ask the developers to make a F77.pm file decision on the SEE ALSO section.

1. overwrite the SEE ALSO section verbatim as in https://github.com/PDLPorters/extutils-f77/issues/7#issue-391680210

2. leave the SEE ALSO section as is

3. to the unmodified current content of the SEE ALSO section add verbatim the sentence as
in https://github.com/PDLPorters/extutils-f77/issues/7#issuecomment-450767562

**Comment by karlglazebrook** [comment]
Woops. Fixed, I think, but let's not over analyse these minors pieces of text!
