### ISSUE TITLE
Erroneous quotes

### ISSUE THREAD

**Issue by wlmb** [PDLPorters/extutils-f77#8]
While building a package I got the following error
    $./Build
    # process_pd_files
    # provides....lib/Photonic/ExtraUtils.pd
    Loaded ExtUtils::F77 version 1.23
    Building Photonic
    cc -shared -O2 -L/usr/local/lib -fstack-protector-strong -o blib/arch/auto/Photonic/ExtraUtils/ExtraUtils.so lib/Photonic/ExtraUtils.o "-L/usr/lib/gcc/x86_64-linux-gnu/8"  -L/usr/lib -lgfortran -lm
fortran/cgtsl.o fortran/dgtsl.o
=>cc: error: "-L/usr/lib/gcc/x86_64-linux-gnu/8": No such file or directory
    cc: error: : No such file or directory
    error building blib/arch/auto/Photonic/ExtraUtils/ExtraUtils.so from lib/Photonic/ExtraUtils.o at /home/mochan/perl5/perlbrew/perls/perl-5.28.0/lib/5.28.1/ExtUtils/CBuilder/Base.pm line 332.

The error is due to the quotes around -L/usr.../8 in the line marked with =>. The error arises in version 1.23 but not in 1.20. Stepping through the execution I found that the error is in line 96 of ExtUtils::F77.pm 

       return( qq{"-L$dir" $append -L/usr/lib -l$lib -lm} );

where there are both qq and "" quotes around -L$dir. I guess it can be fixed removing the double quotes "".

**Comment by mohawk2** [comment]
The quotes are not erroneous. EU::F77 is intended for use with EUMM, which produces command lines (i.e. to be interpreted by a shell) for use by `make`. From the `./Build` above, Photonic is a `Module::Build` distro. It will be using perl as a sort of ersatz shell, and running `cc` with literal strings. Those strings need post-processing to remove the `"` if they are to be used in this way. This is an error in `Module::Build::Pluggable::Fortran` - @mvgrimes.

**Comment by karlglazebrook** [comment]
Not sure I quite get this, why no quotes around:

 $append -L/usr/lib -l$lib

**Comment by mohawk2** [comment]
Because `$lib` is unlikely to have spaces in, since its name is controlled by software authors. By contrast, a `-L` flag, being a directory location, is under the control of software users, and is therefore much less restricted. If software authors ever start naming their libraries things with spaces, I will adjust to keep up :-)

**Comment by mohawk2** [comment]
And to avoid doubt: the rest of the things you quote are *supposed* to be split up into separate "words" - putting quotes round that would be the opposite of what's needed.

**Comment by mohawk2** [comment]
Finally, the above-referenced PR by me on the module which was actually wrong (Module::Build::Pluggable::Fortran) has been accepted and released, and has solved the real problem :-)

**Comment by wlmb** [comment]
Spaces within filenames ought to be declared immoral :)


On Fri, Feb 22, 2019 at 07:24:57PM -0800, mohawk2 wrote:
> And to avoid doubt: the rest of the things you quote are *supposed* to be split up into separate "words" - putting quotes round that would be the opposite of what's needed.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PDLPorters/extutils-f77/issues/8#issuecomment-466611771

-- 

                                                                  o
W. Luis Mochán,                      | tel:(52)(777)329-1734     /<(*)
Instituto de Ciencias Físicas, UNAM  | fax:(52)(777)317-5388     `>/   /\
Apdo. Postal 48-3, 62251             |                           (*)/\/  \
Cuernavaca, Morelos, México          | mochan@fis.unam.mx   /\_/\__/
GPG: 791EB9EB, C949 3F81 6D9B 1191 9A16  C2DF 5F0A C52B 791E B9EB

**Comment by mohawk2** [comment]
Ha ha! No. If the filesystem accepts it, the program needs to handle it.

**Comment by karlglazebrook** [comment]
Check! Got all that.

Karl

**Comment by wlmb** [comment]
I found another (minor) problem with the quotes, while installing
PGPLOT. Maybe not directly related to PDL, but as it is mentioned in
the DEPENDENCIES I bring it up here.

After downloading PGPLOT,

   perl Makefile.PL

yields the message

   Unrecognized argument in LIBS ignored: '"-L/usr/lib/gcc/x86_64-linux-gnu/8"'

Anyway,

    make

works.

    make test

fails in perl 5.28 as '.' is not in @INC, but it passes after editing
test.pl, replacing "test..." by "./test..."

Best regards,

Luis

On Sat, Feb 23, 2019 at 03:14:03PM -0800, Karl Glazebrook wrote:
> Check! Got all that.
> 
> Karl
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PDLPorters/extutils-f77/issues/8#issuecomment-466709940

-- 

                                                                  o
W. Luis Mochán,                      | tel:(52)(777)329-1734     /<(*)
Instituto de Ciencias Físicas, UNAM  | fax:(52)(777)317-5388     `>/   /\
Apdo. Postal 48-3, 62251             |                           (*)/\/  \
Cuernavaca, Morelos, México          | mochan@fis.unam.mx   /\_/\__/
GPG: 791EB9EB, C949 3F81 6D9B 1191 9A16  C2DF 5F0A C52B 791E B9EB

**Comment by karlglazebrook** [comment]
bugger I thought I had fixed that.

“.” by default is sensibly not in most people’s PATHs

What is the OS portable way of doing this?

Karl

**Comment by wlmb** [comment]
On Mon, Feb 25, 2019 at 05:53:42PM -0800, Karl Glazebrook wrote:
> bugger I thought I had fixed that.
> 
> “.” by default is sensibly not in most people’s PATHs
> 
> What is the OS portable way of doing this?
> 

No idea. In Linux I just prepended "./". Maybe the Cwd module can help.

-- 

                                                                  o
W. Luis Mochán,                      | tel:(52)(777)329-1734     /<(*)
Instituto de Ciencias Físicas, UNAM  | fax:(52)(777)317-5388     `>/   /\
Apdo. Postal 48-3, 62251             |                           (*)/\/  \
Cuernavaca, Morelos, México          | mochan@fis.unam.mx   /\_/\__/
GPG: 791EB9EB, C949 3F81 6D9B 1191 9A16  C2DF 5F0A C52B 791E B9EB

**Comment by mohawk2** [comment]
At the top:

`use Cwd 'abs_path';`

On now line 39:

`do abs_path("test$jjj.p");`
